name: Auto Video Creator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
        pip install -r requirements.txt

    - name: Run Script
      run: python src/main.py

    - name: Check Output
      run: ls -R

    - name: Upload Video
      uses: actions/upload-artifact@v4
      with:
        name: video
        path: output/video.mp4
